/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_test;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public String sayHello() {
        return "Hello Gradle";
     }

     public static void main(String[] args) {
        Library app = new Library();
        System.out.println(app.sayHello());
     }
}
